version: "3.8"
services:
  app-search:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy  # ✅ Wait for PostgreSQL to be ready
    environment:
      - DB_NAME=app_search_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db  # Set to 'db' for Docker
      - DB_PORT=5432
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - app-search

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_search_db
    healthcheck:  # ✅ Check if PostgreSQL is ready before starting Django
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
