# Generated by Django 4.2.18 on 2025-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_appdetail_android_version_appdetail_app_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral'), ('nan', 'nan')], default='Neutral', max_length=50),
        ),
    ]
