# Generated by Django 4.2.18 on 2025-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_alter_appreview_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='installs',
            field=models.CharField(max_length=50),
        ),
    ]
