# Generated by Django 4.2.18 on 2025-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_alter_appdetail_installs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
