# Generated by Django 4.2.18 on 2025-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_alter_appdetail_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
