# Generated by Django 5.1.5 on 2025-02-05 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_alter_appdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
