# Generated by Django 5.1.5 on 2025-02-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_appreview_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreview',
            name='status',
        ),
    ]
